[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Budget Tracker Application"
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=4.2.1",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "psycopg2-binary>=2.9.10",
    "python-dotenv>=1.0.1",
    "streamlit>=1.41.1",
]